### ISSUE TITLE
Show terminal name when a custom terminal is created

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/vscode-terminal-tabs#10]

**Comment by jing2si** [comment]
+1

**Comment by abuteler** [comment]
Hi there!
I just installed the extension and I don't see any tabs when I open more than 1 terminal, nor do I see any documentation on how to open terminals via API.
Does this extension work? or was it flunked https://github.com/Microsoft/vscode/issues/13267 ?

**Comment by Tyriar** [comment]
@abuteler you need to setup keybindings as stated in the readme https://github.com/Tyriar/vscode-terminal-tabs#terminal-tabs

**Comment by abuteler** [comment]
Thanks Tyriar!
I had added { "key": "ctrl+shift+oem_plus", "command": "terminalTabs.createTerminal" } in my keybindings, and was having no luck opening terminals using the combination of keys. Not sure what happened, since it's working now.
Thanks again!

**Comment by Tyriar** [comment]
I'm deprecating/archiving the extension since terminal tabs have landed in VS Code. You can enable now with the `terminal.integrated.tabs.enabled` setting which will be on by default in the upcoming version.
