### ISSUE TITLE
Request: terminalTabs.showTerminalNext and Previous

### ISSUE THREAD

**Issue by nancym** [Tyriar/vscode-terminal-tabs#11]
In addition to these commands:

    terminalTabs.showTerminalN: Shows the Nth terminal

It would be very useful to have:

    terminalTabs.showTerminalNext: Shows the next terminal
    terminalTabs.showTerminalPrevious: Shows the previous terminal

Thanks for a great extension!

**Comment by Tyriar** [comment]
Is there any reason the standard commands for this don't work?

```
workbench.action.terminal.focusNext
workbench.action.terminal.focusPrevious
```

**Comment by nancym** [comment]
I didn't know about those, but they work! Here's my `keybindings.json` now:

```json
[
{
    "key": "ctrl+`",
    "command": "terminalTabs.createTerminal"
},
{
    "key": "cmd+right",
    "command": "workbench.action.terminal.focusNext"
},
{
    "key": "cmd+left",
    "command": "workbench.action.terminal.focusPrevious"
}
]
```

Thanks for the tip 😸

**Comment by Tyriar** [comment]
Great :smile:

**Comment by Tyriar** [comment]
Another tip: You can also add a context key to it if you only want the keybinding to work when you have the terminal focused. This could let you override cmd+tab for example.

```js
{
    "key": "cmd+tab",
    "command": "workbench.action.terminal.focusNext",
    "when": "terminalFocus"
}
```
