### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by berkandirim** [Tyriar/vscode-terminal-tabs#12]
I'm on VS Code 1.12.2 . I don't see any tabs in the status bar.

**Comment by Tyriar** [comment]
Please provide more information such as: OS, a screenshot, repro steps (did you just launch?).

**Comment by Tyriar** [comment]
You need to run the extension commands https://github.com/Tyriar/vscode-terminal-tabs#terminal-tabs, you need to manually add keybindings for these as I did not want to override defaults.
