### ISSUE TITLE
terminalTabs.createTerminal doesn't seem to have any effect

### ISSUE THREAD

**Issue by mikemaccana** [Tyriar/vscode-terminal-tabs#13]
I've installed tabbed terminal, and modifed my `keybindings.json` as instructed, but can't get a new tab to open:

<img width="1032" alt="screenshot_5" src="https://user-images.githubusercontent.com/172594/28039464-5493a9ce-65ba-11e7-90c7-7e3cfab832da.png">

Instead, when I press Ctrl T, `^t` appears in the terminal. Am I doing something wrong? 

Note I'm new to VSCode, so if there's some magic I need to do to make this work that isn't mentioned in the docs, I won't know it. Thanks!

**Comment by Tyriar** [comment]
ctrl+t is normally send to be evaluated by the terminal. In order for the command to skip the terminal you need to explicitly add `terminalTabs.createTerminal` to the `terminal.integrated.commandsToSkipShell` setting

**Comment by mikemaccana** [comment]
Thanks! I've added a small contribution to the README for others in future.
