### ISSUE TITLE
Tabs indicator don't show

### ISSUE THREAD

**Issue by rodrigo-brito** [Tyriar/vscode-terminal-tabs#16]
by default the tabs must appear in bottom? I installed in the mac, open more than one terminal and the tabs indicator don't appear.

VS Code: 1.14
macOS Sierra 10.12.4

**Comment by Tyriar** [comment]
You need to call the extension commands, the regular terminal commands will not work. Please see the readme https://github.com/Tyriar/vscode-terminal-tabs

**Comment by rodrigo-brito** [comment]
Thank you!
