### ISSUE TITLE
Feature: Default terminal settings

### ISSUE THREAD

**Issue by BenWildeman** [Tyriar/vscode-terminal-tabs#18]
It would be great if this had a setting for automatically opening terminals. In my local version I have added this, but I would like your thoughts on this before I submit a pull request with this feature. 

Currently I have the following setting:
```json
"terminalTabs.defaultTerminals": [{
  "name": "Terminal Name",
  "directory": "c:\\path\\to\\directory",
  "command" "command to start with when terminal created"
}]
```
## Motivation ##
I personally have a workspace created in VS Code Insiders which has two directories. These directories are our API and Apps repositories. When I use this workspace, I'm constantly opening up 4 terminals. API terminal running API in dev mode, Apps terminal running in dev mode, and subsequent git terminals for managing these repositories.

By adding these terminals to the defaultTerminal settings outlined above within my .code-workspace file, these terminals automatically open when the workspace is opened, saving time and repeating mundane tasks.

## Implementation ##
This is currently achieved by doing the following:
* changing the `"activationEvents"` to `"*"`
* calling the kill active terminal command to remove the stupid lingering terminal on vscode start
* adding a `sendCommand` function to `StatusBarTerminal`
* looping through the default terminals
  * setting name on creation
  * calling `sendCommand` with cd to the specified directory in the setting
  * calling `sendCommand` with the specified command in the setting

## Questions ##
Are you happy with this implementation outlined above? Any suggestions going forward with this?

**Comment by Tyriar** [comment]
I get the motivation but I don't think this is the right place to put the solution.

- There is this extension which aims to solve this problem which I would recommend https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals
- Also https://github.com/Microsoft/vscode/issues/20013 is to add native support for this sort of thing to VS Code without an extension.

I also don't want to add much more to this extension as I'd rather focus efforts on adding splitting https://github.com/Microsoft/vscode/issues/7504 and proper tab support https://github.com/Microsoft/vscode/issues/10546 to VS Code.

**Comment by Tyriar** [comment]
@NitroGhost also thanks for prodding me on this, I did some long overdue dumping of my thoughts into https://github.com/Microsoft/vscode/issues/20013#issuecomment-340026972 and https://github.com/Tyriar/node-pty/issues/151 😄
