### ISSUE TITLE
Multiple tabs don't seem to be working on Visual Studio for Mac

### ISSUE THREAD

**Issue by usmanajmal** [Tyriar/vscode-terminal-tabs#19]
- Just installed **Terminal Tabs** extension. 
- Reloaded Visual Studio Code
- Created new terminals. But all of them still appear under a dropdown instead of a tab. 
<img width="1873" alt="screen shot 2017-11-12 at 4 35 49 pm" src="https://user-images.githubusercontent.com/1510307/32705378-78b519b2-c7c8-11e7-8a07-23782be43313.png">

Can you check this out @Tyriar ?

**Comment by jessegonzalez** [comment]
@usmanajmal that looks like a tab icon in bottom right corner of the screencap.

**Comment by juanpasolano** [comment]
I have the same issue. I don't see any tabs on Mac OS High Sierra

**Comment by Tyriar** [comment]
@usmanajmal you need to manually add keybindings for the commands as mentioned in the readme https://github.com/Tyriar/vscode-terminal-tabs
