### ISSUE TITLE
Support default terminal commands

### ISSUE THREAD

**Issue by kankaristo** [Tyriar/vscode-terminal-tabs#21]
https://github.com/Microsoft/vscode/issues/13267 was closed a few months ago, any update on supporting the default terminal commands?

**Comment by Tyriar** [comment]
It's being stabilized in 1.26 so this could be done when that's released https://github.com/Microsoft/vscode/issues/52574

**Comment by Bessonov** [comment]
@Tyriar any update on this? And I have a bug. If I open vsc, then I have "normal" terminal and I'm forced to close it and open a new "vsc terminal tabs" terminal. It is related to this issue?

**Comment by Tyriar** [comment]
I'm deprecating/archiving the extension since terminal tabs have landed in VS Code. You can enable now with the `terminal.integrated.tabs.enabled` setting which will be on by default in the upcoming version.
