### ISSUE TITLE
Feature: Create Terminal at current file's directory

### ISSUE THREAD

**Issue by MapleHe** [Tyriar/vscode-terminal-tabs#22]
Is it possible ? The new Terminal created by default feature/shortcut "openInTerminal" of vscode will not be recognized by the extension.

**Comment by Tyriar** [comment]
https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here

**Comment by MapleHe** [comment]
Thanks so much but sorry to bother you again. I know the extension you recommend, and I've found that vscode has integrated the feature into its keyboard settings, command name: "openInTerminal". ( vscode for macOS Sierra). However, both of them are not compatible with  the "terminal-tabs" ext, which means, when I create a terminal at current file's folder using "terminal-here" or "openInTerminal",  there will be no tabs added to "terminal-tabs" list (terminal itself works well).

**Comment by Tyriar** [comment]
@MapleHe you want https://github.com/Tyriar/vscode-terminal-tabs/issues/21 which will allow all terminals to get tabs, regardless of how they're created.
