### ISSUE TITLE
Display terminal name instead of terminal number

### ISSUE THREAD

**Issue by fullenw1** [Tyriar/vscode-terminal-tabs#24]
Hi,

If I have several terminals opened,
I don't remember what I have done in terminal 1, 2, 3, and so on...
Icons with the terminal name instead of a number would be very helpful, especially if I am connected to different servers.

**Comment by Tyriar** [comment]
Right now the name is pulled from the process, sometimes this is good (1: node, powershell), sometimes bad (1: bash, 2: bash, ...). This command allows you to set the name for the terminals:

![image](https://user-images.githubusercontent.com/2193314/47823883-83d46d00-dd27-11e8-91fa-b9ea940dd6b0.png)

There are also some extensions which help manages these such as https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals
