### ISSUE TITLE
Save terminal configuration per project 

### ISSUE THREAD

**Issue by lejafo** [Tyriar/vscode-terminal-tabs#25]
It would be very useful if this extension would support saving terminal configurations per projects. For example, for my project I usually use four named terminals: 

- git
- webApi (.Net core)
- Angular build
- Angular developing

And I want to be sure that when I open my project, all four terminals will open too (with it's own predefined path).

Thank you!

**Comment by Tyriar** [comment]
You can accomplish this with VS Code's workspace settings. https://code.visualstudio.com/docs/getstarted/settings

**Comment by lonix1** [comment]
@zejafo Did you figure it out? I also have that setup! :smile: 

Not sure what settings to use.

**Comment by Tyriar** [comment]
@lonix1 you can configure most settings per workspace by using the workspace settings:

<img width="187" alt="Screen Shot 2019-05-08 at 5 05 07 PM" src="https://user-images.githubusercontent.com/2193314/57416077-748d1b00-71b3-11e9-96cf-2a289961e968.png">

**Comment by lonix1** [comment]
Yeah I use workspace settings so I know about them - but I don't understand how OP's request can be accomplished that way.

I'm under the impression this extension doesn't open anything on project open, so there's nothing to configure...

**Comment by Tyriar** [comment]
@lonix1 ah I missed that part actually, that's out of the scope of this extension but can be accomplished with this one https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

**Comment by lonix1** [comment]
That extension is awesome, thanks for the recommendation! :+1: 

@zejafo Just tried it, worth a look.
