### ISSUE TITLE
Is this extension supposed to work with the latest insiders ?

### ISSUE THREAD

**Issue by ymolists** [Tyriar/vscode-terminal-tabs#26]
I tried the extension in the latest vscode insider `code-insider-1546496535` and it does not show anything when i open a new terminal. I also tried running the extension in the debugger and the debugger is not stopping at the activate function.

Did something change in the terminal API or i just have a messed up environment ?

**Comment by ymolists** [comment]
FTR if i try to create a terminal with the command `terminalTabs.createTerminal` or `terminalTabs.createNamedTerminal` those terminals show up in the status bar. All other terminals are not visible in the status bar.

**Comment by Tyriar** [comment]
See https://github.com/Tyriar/vscode-terminal-tabs#limitations
