### ISSUE TITLE
[Feature Request] Middle-click close terminal

### ISSUE THREAD

**Issue by lonix1** [Tyriar/vscode-terminal-tabs#27]
In most tabbed apps, the middle-click button can be used to close a tab.

It would be nice in this case to middle-click on a terminal icon, and for it to be terminated (forcibly if necessary). Exactly like clicking the "Kill Terminal" / garbage bin button.

**Comment by Tyriar** [comment]
I don't think the API allows this, but this project is just a stop-gap solution before https://github.com/microsoft/vscode/issues/10546 is implemented

**Comment by lonix1** [comment]
I didn't realise you were on the vscode team... I guess you went rogue and made your own extensions! :wink: 

The proposal in that issue is good, but what you've done here is great - I like the little buttons at the bottom. Pity API doesn't support middle/right click functionality though.

I really enjoy using this extension - thanks for making it!

**Comment by Tyriar** [comment]
@lonix1 yeah, it's much easier to pop a few buttons into the status bar in an extension than do actual tab support in the core product 😛
