### ISSUE TITLE
Feature request: Pin the icon on the Status bar; + icon; Minimize on second click.

### ISSUE THREAD

**Issue by viniciusmi00** [Tyriar/vscode-terminal-tabs#29]
Hello guys. I'm almost 100% satisfied with Terminal Tabs. I would like to leave some requests so that are 100% satisfied if it is implemented.

1° - Pin the icon on the Status bar. Whenever we open the VS Code, the terminal icon with the number 1 in the Status Bar could already appears, as it is the first terminal that is already there when VS Code is opened.
Note: I came to this plugin because I just wanted to have a terminal icon in the Status Bar. I'm still with the plugin it because I've seen that it has more good features, but having to create the icon by the Task every time, it's very annoying. So I'm going to vote to be integrated into the VS Code natively, but do not forget to ask for the first icon always fixed in the Status Bar.

2° - If we have the first icon always fixed in the status bar, there could be a + button to the right of the icon, which when it is clicked it creates another Tab of the terminal, without us having to type anything. With each click on the icon +, create another Tab on the left of the icon and drag + it a little forward.

3° - The Terminal Tabs buttons in the Status Bar need to be given an option to minimize the terminal. If we click once on the icon the terminal appears, but when clicking the second time, instead of minimizing the terminal, it remains open. Put the option: by clicking for second time in the Terminal Tab icon of the terminal that is open, this terminal minimizes. Like as in the Problems icon, which is just on the left.

Thanks for this great plugin.

**Comment by Tyriar** [comment]
I'm not planning on improving this extension anymore, keep an eye on https://github.com/microsoft/vscode/issues/10546 which will add proper tabs to the terminal.
