### ISSUE TITLE
Icon at Status bar - click to open / click to close

### ISSUE THREAD

**Issue by kanlukasz** [Tyriar/vscode-terminal-tabs#30]
When i click your terminal icon, the terminal panel will open
It would be nice if I click this icon again and the terminal panel will hide
Is it possible?

![obraz](https://user-images.githubusercontent.com/30685349/73427923-2703a000-4338-11ea-96a0-951e047fe1fd.png)

**Comment by Tyriar** [comment]
There's no way to tell whether a terminal is visible in VS Code's API right now. https://github.com/microsoft/vscode/issues/10546 is probably going to happen this year so I'm not planning on investing more into this extension.
