### ISSUE TITLE
Image in readme works fine on GitHub but not on marketplace or within vscode

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/vscode-terminal-tabs#9]
I'm using markdown:

``` md
![](images/preview.png)
```

This is the same as I use in https://github.com/Tyriar/vscode-theme-glacier/blob/master/README.md but this doesn't work for some reason in [the marketplace](https://marketplace.visualstudio.com/items?itemName=Tyriar.terminal-tabs).

**Comment by Tyriar** [comment]
@joaomoreno any idea why this is happening?

**Comment by joaomoreno** [comment]
You might need to add some `alt` text, like `![for accessibility reasons](images/preview.png)`

**Comment by Tyriar** [comment]
Seems like an odd thing to enforce considering "terminal tabs preview" is pretty meaningless to be read out by a screen reader.

**Comment by Tyriar** [comment]
Yep that fixed it
